server:
  port: 8881
eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer2:8882/eureka/

spring:
  application:
    name: server-center