eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8881/eureka/
server:
  port: 8889

#服务名
spring:
  application:
    name: server-gateway
  cloud:
    gateway:
      filter:
        remove-non-proxy-headers:
          headers:
          - dummy
      routes:
      - id: app
        # 重点！/info必须使用http进行转发，lb代表从注册中心获取服务
        uri: lb://SERVICE-RIBBON
        predicates:
        # 重点！转发该路径！,/userapi/**,
        - Path=/api-a/**
        # http://localhost:6601/userapi/user/users/2, 必须加上StripPrefix=1，否则访问服务时会带上userapi
        #而不是我们期望的去掉userapi，只保留**部分
        filters:
        - StripPrefix=1
      - id: api-b
        uri: lb://service-feign
        predicates:
        - Path=/api-b/**
        filters:
        - StripPrefix=1