#服务器配置
server:
  undertow:
    io-threads: 2 # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    worker-threads: 16 # 阻塞任务线程池, 当执行类似servlet请求阻塞IO操作, undertow会从这个线程池中取得线程
    # 它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
    buffer-size: 512  # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    #buffers-per-region: 512 # 每个区分配的buffer数量 , 所以pool的大小是buffer-size * buffers-per-region
    direct-buffers: true # 是否分配的直接内存(NIO直接分配的堆外内存)
  port: 8886
#数据库配置${mysql.host} 读取远程配置文件
spring:
  application:
    name: services-consumer
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# 启用端点 env endpoint.env.enabled=true
management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*" #获取全部环境属性 "*" 表示开启全部
feign:
  hystrix:
    enabled: true
#开启sql日志打印
#logging:
#    level:
#      com.qurich.mapper: DEBUG #打印sql日志