#服务器配置
server:
  undertow:
    io-threads: 2 # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    worker-threads: 16 # 阻塞任务线程池, 当执行类似servlet请求阻塞IO操作, undertow会从这个线程池中取得线程
    # 它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
    buffer-size: 512  # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    #buffers-per-region: 512 # 每个区分配的buffer数量 , 所以pool的大小是buffer-size * buffers-per-region
    direct-buffers: true # 是否分配的直接内存(NIO直接分配的堆外内存)
  port: 80
#数据库配置${mysql.host} 读取远程配置文件
spring:
  application:
    name: services-user
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  datasource:
    name: qurich_user
    url: jdbc:mysql://${mysql.host}:3306/qurich_user?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: ${mysql.username}
    password: Ckik22*/224WPu&
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 100
    initialSize: 10
    maxWait: 60000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 100
  mvc:
    view:
      prefix: /templates/
      suffix: .ftl
freemarker:
  allowRequestOverride: false
  allowSessionOverride: false
  requestContextAttribute: request
  cache: false
  checkTemplateLocation: true
  contentType: text/html
  exposeRequestAttributes: true
  exposeSessionAttributes: false
  exposeSpringMacroHelpers: false
  suffix: .ftl
  templateEncoding: UTF-8
  templateLoaderPath: classpath:/templates/  #表示所有的模板文件都放在该目录下
  spring.freemarker.settings:
    log_template_exceptions: false
    date_format: yyyy-MM-dd
    time_format: HH:mm:ss
    datetime_format: yyyy-MM-dd HH:mm:ss
mybatis:
  type-aliases-package: com.qurich.model
  type-handlers-package: com.qurich.mapper
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 180

#熔断器
feign:
  hystrix:
    enabled: true

# 启用端点 env endpoint.env.enabled=true
management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*" #获取全部环境属性 "*" 表示开启全部
#开启sql日志打印
#logging:
#    level:
#      com.qurich.mapper: DEBUG #打印sql日志